apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-jaggu
    image: nginx
    ports:
    - containerPort: 8080
  - name: nginx-jaggu-watcher
    image: afakharany/watcher
